### ISSUE TITLE
Graphics.UI.GLUT.Raw no longer exposed!

### ISSUE THREAD

**Issue by MagneticDuck** [haskell-opengl/GLUT#17]
Many of the functions in Graphics.UI.GLUT.Raw.Functions are very useful and necessary; an example pertinant to my project is glutIgnoreKeyRepeat. The decision to move Graphics.UI.GLUT.Raw and submodules to the other-modules section, thus, leaves me with no way to call those very useful low level bindings without either making bindings to them in my own project or modifying this package locally.

What was the motivation for this change? Can we get it changed back?

**Comment by svenpanne** [comment]
(Going though old bug reports...)

The Raw stuff is considered an implementation detail and therefore it should not be exposed. Nevertheless, all features from Raw should have easily usable counterparts in the non-Raw API, if not, that's a bug. In your example: What exactly is missing for you? The key repeat feature you are talking about is exposed as [perWindowKeyRepeat](https://hackage.haskell.org/package/GLUT-2.6.0.1/docs/Graphics-UI-GLUT-DeviceControl.html#v:perWindowKeyRepeat).

**Comment by svenpanne** [comment]
Closing this bug due to inactivity. If some concrete feature is missing (currently I see none), please open a bug for it.
