### ISSUE TITLE
Texture binding using VBO's and OGL 4+

### ISSUE THREAD

**Issue by madjestic** [haskell-opengl/GLUT#18]

**Comment by svenpanne** [comment]
The GLUT examples contain e.g. the [example from the first chapter] (https://github.com/haskell-opengl/GLUT/tree/master/examples/RedBook8/Chapter01) of the Red Book and a slight [colored variation](https://github.com/haskell-opengl/GLUT/tree/master/examples/Misc/ColorTriangle) of it.
