### ISSUE TITLE
OpenGL-Tutorial not up-to-date

### ISSUE THREAD

**Issue by blueburningcoder** [haskell-opengl/GLUT#22]
Hi, I wanted to tell you that this Tutorial here ( https://wiki.haskell.org/OpenGLTutorial1 ) is not up to date, since neither `color3f` nor `vertex3f` (used near the bottom of the page) are accessible that way anymore.

**Comment by svenpanne** [comment]
Hmmm, I just tested the code snippets after doing a ``cabal update && cabal install GLUT`` in a fresh sandbox, and everything worked. What exactly doesn't work for you and what versions are you using? (Output of ``ghc --version`` and ``ghc-pkg list``)

**Comment by blueburningcoder** [comment]
my ghc is `version 7.6.3`, the GLUT package itself `2.4.0.0`

the errors I'm getting are:
```
    Not in scope: `color3f'
    Perhaps you meant one of these:
      `color' (imported from Graphics.UI.GLUT),
      `colorv' (imported from Graphics.UI.GLUT)
```
