### ISSUE TITLE
Linking with freeGLUT on OSX

### ISSUE THREAD

**Issue by rumblesan** [haskell-opengl/GLUT#24]
I'm currently building a project on OSX and finding that I can't actually get freeGLUT linking. The installed system version of GLUT is always being used.

Just to confuse matters, I'm also using stack to build and have install freeGLUT with brew.

I realise that OSX is its own special flavour of awkward for this type of thing, but I feel like there should just be some ghc-options flags that I should be able to pass that will make it clear I want to build against freeGLUT and not the system framework. Just can't seem to figure out what they are.

Currently I'm telling stack to explicitly pass ghc the -lGLUT flag, but that doesn't seem to be doing the trick.
https://github.com/rumblesan/improviz/blob/master/stack.yaml#L62-L69

**Comment by svenpanne** [comment]
The Haskell GLUT package dynamically loads the native GLUT library, on non-Windows systems via ``dlopen``. What it actually tries to load on Mac OS X is in the [native part](https://github.com/haskell-opengl/GLUT/blob/f93564a78cc251a696b306f2675b9ae2575ae417/cbits/HsGLUT.c#L53-L56) of the GLUT package. Currently it tries to load GLUT from the public framework path first, then from the system one. It shouldn't be too hard to add another location, but I would need a tested patch. Dynamic linking on Mac OS X is always a bit interesting (read: "non-standard"), and I've got no idea if we need a full absolute path or not, what the freeglut library is actually called on Mac OS X, if we can load it with or without ``.so`` suffix, if we need a version number or not, etc.

So try to add a sensible line before the public framework path and send a patch or pull request. I'm not sure if you need some additional linker flag in the ``.cabal`` file, but I guess you don't.

**Comment by rumblesan** [comment]
Thanks for getting back to me and explaining what's going on.

Adding in a path directly to the homebrew installed version of GLUT does work (/opt/boxen/homebrew/lib/libglut.dylib) in my case.
It's also possible to just add libglut.dylib and then set the LD_LIBRARY_PATH to the right directory and have everything link as expected as well.
I'll raise a pull request with the changes in and close this.
