### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by noughtmare** [haskell-opengl/GLUT#27]
https://github.com/haskell-opengl/GLUT/blob/95db3fd708af3b54771b90f7cf589a537ff85798/src/Graphics/UI/GLUT/Fonts.hs#L58-L62

> For a stroke font, return the width in units.

Should this be: "For a stroke font, return the **height** in units."

**Comment by svenpanne** [comment]
Thanks for the hint, fixed...
